addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.1")
addSbtPlugin("com.typesafe.sbt" % "sbt-web" % "1.4.4")
addSbtPlugin("com.github.ahjohannessen" % "sbt-http4s-web" % "0.0.6")
addSbtPlugin("com.vmunier" % "sbt-web-scalajs" % "1.0.10-0.6")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.31")
addSbtPlugin("org.irundaia.sbt" % "sbt-sassify" % "1.4.13")
