addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.7.2")
addSbtPlugin("org.irundaia.sbt" % "sbt-sassify" % "1.4.13")
//addSbtPlugin("com.typesafe.sbt" % "sbt-uglify" % "2.0.0")
//addSbtPlugin("com.typesafe.sbt" % "sbt-jshint" % "1.0.6")
//addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.9")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.1.0-M13-4")
